# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    paths:
      - 'data/**'
      - 'scripts/QA_QC/checks.R'
  pull_request:
    paths:
      - 'data/**'
      - 'scripts/QA_QC/checks.R'

name: QA_QC_checks

jobs:
  QA_QC_checks:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "dplyr", "readr"))
          # remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      # - name: Check
      #   run: |
      #     options(crayon.enabled = TRUE)
      #     rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
      #   shell: Rscript {0}
      - name: Quality checks
        id: Quality_checks
        run: |
          source("scripts/QA_QC/checks.R")
        shell: Rscript {0}
      - name: Commit new files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add --all
          git commit -am "add data"
          git push     